ip_address_info:
  - {
    ip_address: "192.168.1.135",
    lidar_name: "livox_front_left",
  }
  - {
    ip_address: "192.168.1.146",
    lidar_name: "livox_rear_right",
  }
  - {
    ip_address: "192.168.1.200",
    lidar_name: "hesai_top_lidar",
  }
