nodes_list: [
    "/box_assemble",
    "/box_assemble_calc_node",
    "/platform_communication",
    "/cti_cmd_vel_smoother_node",
    "/decision_planning_node",
    "/cti_detect_plan_node",
    "/cti_globalmap_planner_node",
    "/cti_ground_filter",
    "/cti_ledshow_node",
    "/cti_local_scheduler",
    "/cti_object_map",
    "/cti_prediction",
    "/vector_map_loader_node",
    "/lidar_combine",
    "/localization_node",
    "/obstacle_speed_node",
    "/robot_config",
    "/waypoint_follower_node",
    "/cti_chassis_data_node",
    "/cti_chassis_handle_node",
  ]
